"""
Simple PDF Report Generator using ReportLab
"""

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
import os
from datetime import datetime


def generate_pdf(case_id, entities, relations, contradictions, confidence, search_results, output_dir="reports"):
    """Generate an explainable investigation PDF report."""
    os.makedirs(output_dir, exist_ok=True)
    filename = os.path.join(output_dir, f"case_{case_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf")

    doc = SimpleDocTemplate(filename, pagesize=A4)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("Title", parent=styles["Heading1"], alignment=TA_CENTER, spaceAfter=20)
    heading = styles["Heading2"]
    normal = styles["Normal"]

    story = []

    # Title
    story.append(Paragraph("AI Crime Investigator", title_style))
    story.append(Paragraph(f"Case Report — {case_id}", styles["Heading2"]))
    story.append(Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", normal))
    story.append(Spacer(1, 20))

    # Confidence
    story.append(Paragraph("Evidence Confidence Score", heading))
    pct = confidence.get("percentage", 0)
    story.append(Paragraph(f"<b>{pct}%</b>", styles["Heading3"]))
    breakdown = confidence.get("breakdown", {})
    story.append(Paragraph(
        f"Prior: {breakdown.get('prior', 0)} | "
        f"Entities: +{breakdown.get('entities', 0)} | "
        f"Relations: +{breakdown.get('relations', 0)} | "
        f"Contradiction Penalty: -{breakdown.get('contradiction_penalty', 0)}",
        normal
    ))
    story.append(Spacer(1, 15))

    # Entities
    story.append(Paragraph("Extracted Entities", heading))
    if entities:
        data = [["Entity", "Type"]]
        for e in entities:
            data.append([e["text"], e["type"]])
        t = Table(data, colWidths=[3*inch, 2*inch])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2c3e50")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
        ]))
        story.append(t)
    else:
        story.append(Paragraph("No entities extracted.", normal))
    story.append(Spacer(1, 15))

    # Relations
    story.append(Paragraph("Relationships", heading))
    if relations:
        data = [["Source", "Relation", "Target"]]
        for r in relations:
            data.append([r["source"], r["relation"], r["target"]])
        t = Table(data, colWidths=[2*inch, 1.5*inch, 2*inch])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2c3e50")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ]))
        story.append(t)
    else:
        story.append(Paragraph("No relationships found.", normal))
    story.append(Spacer(1, 15))

    # Contradictions
    story.append(Paragraph("Contradictions / Flags", heading))
    if contradictions:
        for c in contradictions:
            story.append(Paragraph(f"⚠ {c.get('message', str(c))}", normal))
            story.append(Spacer(1, 5))
    else:
        story.append(Paragraph("No contradictions detected.", normal))
    story.append(Spacer(1, 15))

    # Search paths
    if search_results:
        story.append(Paragraph("Investigation Path Search", heading))
        for algo, result in search_results.items():
            status = "Found" if result.get("found") else "Not found"
            story.append(Paragraph(f"<b>{algo}</b>: {status} (length: {result.get('length')})", normal))
            for line in result.get("log", []):
                story.append(Paragraph(line, normal))
            story.append(Spacer(1, 8))

    story.append(Spacer(1, 30))
    story.append(Paragraph("— End of Report — Generated by AI Crime Investigator", 
                          ParagraphStyle("Footer", parent=normal, alignment=TA_CENTER, fontSize=9)))

    doc.build(story)
    return filename
